//-----------------------------1-----------------------------
//-----------------------------What Are .d.ts Files?-----------------------------
/*
--> Declaration files (.d.ts) contain ONLY type information — no runtime code.
    They describe the shape of JavaScript code so TypeScript can type-check it.

    Where they come from:
      1. Auto-generated by tsc when `declaration: true` in tsconfig (see /dist/*.d.ts)
      2. Bundled inside npm packages (look for "types" field in package.json)
      3. Installed separately via @types packages (DefinitelyTyped)
      4. Written manually for untyped JS code
*/

//-----------------------------2-----------------------------
//-----------------------------Reading @types Packages-----------------------------
/*
--> @types packages live in node_modules/@types/<package>/
    They contain .d.ts files that TS loads automatically.

    Example: @types/express
      node_modules/@types/express/index.d.ts contains:
        - interface Request { ... }
        - interface Response { ... }
        - function express(): Express;

    How TS finds them:
      1. "types" or "typeRoots" in tsconfig.json
      2. By default, TS includes all @types/* in node_modules
      3. Our tsconfig has "types": [] — meaning NO auto-inclusion,
         so we'd need to add e.g. "types": ["node"] to use @types/node

    To install:
      npm i -D @types/express    // types for express
      npm i -D @types/node       // types for Node.js built-ins
*/

//-----------------------------3-----------------------------
//-----------------------------Anatomy of a .d.ts File-----------------------------
/*
--> A declaration file uses `declare` to describe shapes without implementation.
    Compare the compiled output in /dist/1-init.d.ts with the source 1-init.ts.
*/

// If you had an untyped JS utility library, you'd write a .d.ts like this:

// --- imagine file: math-utils.d.ts ---
// declare function add(a: number, b: number): number;
// declare function multiply(a: number, b: number): number;
// declare const PI: number;

// --- imagine file: config.d.ts ---
// declare interface AppConfig {
//   apiUrl: string;
//   port: number;
//   debug: boolean;
// }
// declare const config: AppConfig;

//-----------------------------4-----------------------------
//-----------------------------Declaring Modules-----------------------------
/*
--> When you import a JS package that has no types and no @types package,
    TS will throw: "Could not find a declaration file for module 'xyz'."
    You can create a custom declaration to fix this.
*/

// Create a file like: declarations.d.ts (or any .d.ts file in your project)
// declare module "untyped-lib" {
//   export function doSomething(input: string): number;
//   export default function init(): void;
// }

// Shorthand: declare the entire module as `any` (quick fix, less safe)
// declare module "legacy-lib";
// Now: import anything from "legacy-lib" → type is any

//-----------------------------5-----------------------------
//-----------------------------Module Augmentation-----------------------------
/*
--> You can ADD new properties to existing types from third-party packages.
    This uses declaration merging on the module's interfaces.
*/

// Example: adding a custom property to Express Request
// In a file like: express.d.ts
//
// import "express";
// declare module "express" {
//   interface Request {
//     userId?: string;
//     role?: "admin" | "user";
//   }
// }
//
// Now req.userId and req.role are recognized in all Express handlers.

//-----------------------------6-----------------------------
//-----------------------------Global Declarations (declare global)-----------------------------
/*
--> `declare global` lets you add types to the global scope FROM a module file.
    Any file with a top-level import or export is a module.
    Inside `declare global { }` you can:
      - Extend existing global interfaces (Window, globalThis, NodeJS.Process…)
      - Add brand-new global variables, functions, or types
    The block only affects types — it doesn't create runtime values.
*/

// Step 1: Extend the global scope with custom types
declare global {
  // Add properties to the browser's Window interface
  interface Window {
    __APP_VERSION__: string;
    analytics: { track(event: string, data?: Record<string, unknown>): void };
  }

  // Declare a global variable that exists at runtime (e.g. injected by a script tag)
  var APP_ENV: "development" | "staging" | "production";

  // Declare a global function (e.g. exposed by a legacy script)
  function showToast(message: string, duration?: number): void;

  // Add a brand-new global interface accessible anywhere without import
  interface RuntimeConfig {
    apiUrl: string;
    featureFlags: Record<string, boolean>;
  }
}

// Step 2: Now use them — TS recognises these globally

// Window properties
window.__APP_VERSION__ = "2.1.0";
window.analytics.track("page_view", { page: "/home" });

// Global variable
console.log(APP_ENV); // "development" | "staging" | "production"

// Global function
showToast("Settings saved!", 3000);

// Global interface (no import needed)
const runtimeConfig: RuntimeConfig = {
  apiUrl: "https://api.example.com",
  featureFlags: { darkMode: true, betaSearch: false },
};

/*
--> When to use `declare global`:
    1. Your app injects globals at startup (env vars, config, analytics SDKs)
    2. You're augmenting Window / NodeJS.ProcessEnv for environment variables
    3. You're writing a library that attaches to globalThis

--> Common real-world pattern: typing process.env
*/

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      DATABASE_URL: string;
      JWT_SECRET: string;
      PORT?: string;
    }
  }
}

// Now process.env is typed — no more (string | undefined) guessing
// const dbUrl: string = process.env.DATABASE_URL;
// const port: number = parseInt(process.env.PORT ?? "3000");

//-----------------------------7-----------------------------
//-----------------------------Practical: Exploring a Real .d.ts-----------------------------
/*
  Exercise: open node_modules/typescript/lib/lib.es5.d.ts and look for:

    interface Array<T> {
      length: number;
      push(...items: T[]): number;
      pop(): T | undefined;
      map<U>(callbackfn: (value: T, index: number, array: T[]) => U): U[];
      ...
    }

  This is how TS knows that [1,2,3].map(x => x.toString()) returns string[].
  Every built-in method you use is typed in these lib.*.d.ts files.
*/

//-----------------------------8-----------------------------
//-----------------------------Summary: tsconfig Keys for Declarations-----------------------------
/*
  | tsconfig option     | Purpose                                          |
  |---------------------|--------------------------------------------------|
  | "declaration"       | Generate .d.ts files alongside .js output        |
  | "declarationMap"    | Generate .d.ts.map for Go-to-Definition in IDEs  |
  | "types"             | Which @types packages to auto-include            |
  | "typeRoots"         | Folders to search for type declarations           |
  | "skipLibCheck"      | Skip type-checking .d.ts files (faster builds)   |
*/
